applicationPort: 1234
image:
  repository: sbpocacr.azurecr.io
  pullPolicy: Always

replicaCount: 1

imagePullSecrets:
- name: acr-registry

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    meta.helm.sh/release-name: mb-poc-helm                                                                                                                                                         
    meta.helm.sh/release-namespace: feature-poc
  kubernetes.io/ingress.class: nginx
  hosts:
    - host: testmyapp.io
      paths:
        - path: /mbpoc(/|$)(.*)
          pathType: Prefix
  tls: []
